### ISSUE TITLE
DRL solutions got disjoint errors when evaluating with eval2008.pl

### ISSUE THREAD

**Issue by Lin-Li-19** [haiguanl/DQN_GlobalRouting#1]
After running the command:  **python GenSolEvalComp_Pipeline.py --benchNumber 100 --gridSize 8 --netNum 20 --capacity 4 --maxPinNum 5 --reducedCapNum 3**   I got 100 DRL solutions, but when evaluating with eval2008.pl, most of them met disjoint errors.

> python Evaluation.py
> net A1 pin (42,37,1) not attached
> net A1 pin (58,17,1) not attached
> net A1 pin (77,31,1) not attached
> ERROR net A1 disjoint at eval2008.pl line 397, <RFILE> line 13.

It seems that the DRL solutions obtained from DRN_GlobalRouting are incomplete. How can I solve the problem?

Thanks

**Comment by cancerwower** [comment]
I encountered the same problem, how did you solve it?
